# Generated by Django 5.1.3 on 2024-11-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_upload_converted_file_upload_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(default='English', max_length=50),
        ),
    ]
